import express from "express";
const router = express.Router();

import { userRoute } from "../modules/usersAuth/user.route";
import { authRoute } from "../modules/usersAuth/auth.route";
import { reportRoute } from "../modules/reports/report.route";
import { commentRoute } from "../modules/comments/comment.route";
import { partnerAdRoute } from "../modules/partnerAds/partnerAd.route";
import { contactRoute } from "../modules/contacts/contact.route";
import { localMissionRoute } from "../modules/localMissions/localMission.route";
import { pointRoute } from "../modules/points/point.route";
import { stripeWebhookHandler } from "../webHook/stripe.webhook";
import { paymentRoute } from "../modules/payment/payment.routes";
import { donationRoute } from "../modules/donation/donation.routes";
import { notificationRoute } from "../modules/notifications/notification.route";
import { paypalWebhookHandler } from "../webHook/paypal.webhook";
import { chatRoute } from "../modules/community/chat/chat.routes";
import { chatLikeRoute } from "../modules/community/chatlike/chatlike.routes";
import { solidarityRoute } from "../modules/solidarity/solidarity.route";
import { rewardRoute } from "../modules/rewards/reward.route";
import { storyRoute } from "../modules/stories/stories.routes";
import { donationProofRoute } from "../modules/donationProofs/donationProof.route";
import { adminRoute } from "../modules/admin/admin.route";
import { privateChatRoute } from "../modules/community/privatechat/privatechat.routes";
import { myanimalRoute } from "../modules/myanimal/myanimal.routes";
import { chatReportRoute } from "../modules/community/chatreport/chatreport.routes";
import { faqRoute } from "../modules/faq/faq.route";
import { settingsRoute } from "../modules/settings/settings.route";
import { supportMessageRoute } from "../modules/supportMessages/supportMessage.route";
import { friendRoute } from "../modules/friends/friend.routes";

router.use("/user", userRoute);
router.use("/auth", authRoute);
router.use("/reports", reportRoute);
router.use("/comments", commentRoute);
router.use("/partner-ads", partnerAdRoute);
router.use("/local-missions", localMissionRoute);
router.use("/points", pointRoute);
router.use("/contacts", contactRoute);
// Webhook — raw body লাগবে তাই আলাদা
router.post("/webhook/stripe", stripeWebhookHandler);
router.post("/webhook/paypal", paypalWebhookHandler);

router.use("/payments", paymentRoute);
router.use("/donations", donationRoute);
router.use("/notifications", notificationRoute);
router.use("/community/chat", chatRoute);
router.use("/community/chat", chatLikeRoute);
router.use("/solidarity", solidarityRoute);
router.use("/rewards", rewardRoute);
router.use("/community/stories", storyRoute);
router.use("/donation-proofs", donationProofRoute);
router.use("/admin", adminRoute);
router.use("/community/private", privateChatRoute);
router.use("/myanimal", myanimalRoute);
router.use("/community/chat-reports", chatReportRoute);
router.use("/faq", faqRoute);
router.use("/settings", settingsRoute);
router.use("/support-messages", supportMessageRoute);
router.use("/friends", friendRoute);

export default router;
